### ISSUE TITLE
where download?

### ISSUE THREAD

**Issue by UnemployedAutist** [AlexanderMaxRanabel/FaxHax#1]
where download?

**Comment by AlexanderMaxRanabel** [comment]
Holy shit i forgot to add source code(ill add it in a few hours)

**Comment by AlexanderMaxRanabel** [comment]
I didnt really code anything its 98 percent forgehax

**Comment by AlexanderMaxRanabel** [comment]
Ok there are should be a release and source code now

**Comment by UnemployedAutist** [comment]
thanks
